package podcast

// RSS 2.0 + iTunes-namespace parsing, clean-room from the spec on
// encoding/xml — the same shape as internal/bookscan's EPUB and CBZ readers,
// and for the same reason: the format is small, the stdlib already has the
// parser, and a dependency here would buy nothing but a supply chain.
//
// The governing assumption is that feeds are BAD. Podcast RSS is generated by
// hundreds of tools over twenty years and conforms to nothing in particular:
// dates in half a dozen formats, durations as seconds or as h:mm:ss, missing
// GUIDs, missing enclosures, both `itunes:image href=` and `<image><url>`, and
// entities that no validator ever saw. So every field is optional, every parse
// failure degrades that one field, and only two things can fail a whole
// episode: no audio URL, or no title. An unusable episode is dropped; an
// unusable feed is an error. Nothing here panics on input.

import (
	"encoding/xml"
	"errors"
	"fmt"
	"html"
	"io"
	"strconv"
	"strings"
	"time"
)

// Feed is a parsed podcast, reduced to what Hespera actually renders.
type Feed struct {
	Title       string
	Description string
	Author      string
	Link        string // the show's home page
	ImageURL    string
	Episodes    []Episode
}

// Episode is one item. GUID is the feed's own identity for it and is what
// de-duplicates across refreshes; when a feed omits it, the audio URL stands in
// (that is what the spec suggests and what other clients do).
type Episode struct {
	GUID        string
	Title       string
	Description string
	AudioURL    string
	AudioType   string
	AudioBytes  int64
	Duration    int // seconds; 0 = unknown
	Published   time.Time
	EpisodeNo   int
	SeasonNo    int
	ImageURL    string
}

// --- the wire shapes -------------------------------------------------------
//
// Deliberately minimal: encoding/xml ignores elements with no matching field,
// so listing only what is used means a feed carrying anything else parses
// fine rather than failing on a surprise.

type rssRoot struct {
	XMLName xml.Name   `xml:"rss"`
	Channel rssChannel `xml:"channel"`
}

type rssChannel struct {
	Title       string    `xml:"title"`
	Description string    `xml:"description"`
	Link        string    `xml:"link"`
	Author      string    `xml:"author"` // itunes:author
	Summary     string    `xml:"summary"`
	Image       rssImage  `xml:"image"`
	Items       []rssItem `xml:"item"`
}

// rssImage covers both spellings at once: RSS's <image><url>…</url></image>
// and iTunes' <itunes:image href="…"/>. Whichever the feed used, one of these
// is populated; pickImage prefers the href because iTunes art is the square
// cover art clients actually want.
type rssImage struct {
	URL  string `xml:"url"`
	Href string `xml:"href,attr"`
}

type rssItem struct {
	Title       string       `xml:"title"`
	Description string       `xml:"description"`
	Summary     string       `xml:"summary"` // itunes:summary
	GUID        string       `xml:"guid"`
	PubDate     string       `xml:"pubDate"`
	Duration    string       `xml:"duration"` // itunes:duration
	Episode     string       `xml:"episode"`  // itunes:episode
	Season      string       `xml:"season"`   // itunes:season
	Image       rssImage     `xml:"image"`
	Enclosure   rssEnclosure `xml:"enclosure"`
}

type rssEnclosure struct {
	URL    string `xml:"url,attr"`
	Type   string `xml:"type,attr"`
	Length string `xml:"length,attr"`
}

// ParseFeed turns feed bytes into a Feed.
//
// Strict:false and CharsetReader are both load-bearing on real feeds: strict
// mode rejects the undeclared HTML entities (&nbsp;, &mdash;) that show notes
// are full of, and plenty of feeds declare a non-UTF-8 encoding they then do
// not honour. Neither is worth failing a subscription over.
func ParseFeed(body []byte) (*Feed, error) {
	dec := xml.NewDecoder(strings.NewReader(string(body)))
	dec.Strict = false
	dec.CharsetReader = func(_ string, input io.Reader) (io.Reader, error) {
		// Treat every declared charset as UTF-8 rather than pulling in an
		// encoding table. A mislabelled feed then yields mojibake in one field
		// instead of refusing to parse at all.
		return input, nil
	}

	var root rssRoot
	if err := dec.Decode(&root); err != nil {
		return nil, fmt.Errorf("not a parseable RSS feed: %w", err)
	}
	ch := root.Channel
	if strings.TrimSpace(ch.Title) == "" && len(ch.Items) == 0 {
		return nil, errors.New("no channel title and no items — not a podcast feed")
	}

	f := &Feed{
		Title:       clean(ch.Title),
		Description: clean(firstNonEmpty(ch.Description, ch.Summary)),
		Author:      clean(ch.Author),
		Link:        strings.TrimSpace(ch.Link),
		ImageURL:    pickImage(ch.Image),
	}

	for _, it := range ch.Items {
		ep, ok := episodeFrom(it)
		if !ok {
			continue // no audio or no title: nothing to play and nothing to show
		}
		f.Episodes = append(f.Episodes, ep)
	}
	if f.Title == "" {
		f.Title = "Untitled podcast"
	}
	return f, nil
}

func episodeFrom(it rssItem) (Episode, bool) {
	audio := strings.TrimSpace(it.Enclosure.URL)
	title := clean(it.Title)
	if audio == "" || title == "" {
		return Episode{}, false
	}
	// A feed that points its audio somewhere unusable is not worth storing —
	// catching it here means the play path never meets a URL that was never
	// going to work.
	if _, err := ValidateURL(audio); err != nil {
		return Episode{}, false
	}

	guid := strings.TrimSpace(it.GUID)
	if guid == "" {
		guid = audio
	}
	size, _ := strconv.ParseInt(strings.TrimSpace(it.Enclosure.Length), 10, 64)
	return Episode{
		GUID:        guid,
		Title:       title,
		Description: clean(firstNonEmpty(it.Description, it.Summary)),
		AudioURL:    audio,
		AudioType:   strings.TrimSpace(it.Enclosure.Type),
		AudioBytes:  size,
		Duration:    parseDuration(it.Duration),
		Published:   parseDate(it.PubDate),
		EpisodeNo:   atoiSafe(it.Episode),
		SeasonNo:    atoiSafe(it.Season),
		ImageURL:    pickImage(it.Image),
	}, true
}

// parseDuration reads itunes:duration, which the spec allows in three forms
// and which feeds use in all three: bare seconds, mm:ss, and hh:mm:ss. Garbage
// yields 0, meaning "unknown", which the player already tolerates.
func parseDuration(s string) int {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0
	}
	parts := strings.Split(s, ":")
	// Fractional seconds appear in the wild ("1830.5"); take the whole part.
	if i := strings.IndexByte(parts[len(parts)-1], '.'); i >= 0 {
		parts[len(parts)-1] = parts[len(parts)-1][:i]
	}
	var total int
	for _, p := range parts {
		n, err := strconv.Atoi(strings.TrimSpace(p))
		if err != nil || n < 0 {
			return 0
		}
		total = total*60 + n
	}
	if len(parts) > 3 {
		return 0
	}
	return total
}

// pubDateFormats are the shapes seen on real feeds. RFC1123Z is what the spec
// asks for; the rest are what generators actually emit — single-digit days,
// missing seconds, named zones, and bare ISO dates.
var pubDateFormats = []string{
	time.RFC1123Z,
	time.RFC1123,
	"Mon, 2 Jan 2006 15:04:05 -0700",
	"Mon, 2 Jan 2006 15:04:05 MST",
	"Mon, 2 Jan 2006 15:04 -0700",
	"Mon, 02 Jan 2006 15:04 -0700",
	time.RFC3339,
	"2006-01-02 15:04:05",
	"2006-01-02",
}

// parseDate returns the zero time when nothing matches. The zero value is
// meaningful here — it sorts an undated episode to the bottom rather than
// inventing "now", which would make it look like the newest episode forever.
func parseDate(s string) time.Time {
	s = strings.TrimSpace(s)
	if s == "" {
		return time.Time{}
	}
	for _, f := range pubDateFormats {
		if t, err := time.Parse(f, s); err == nil {
			return t.UTC()
		}
	}
	return time.Time{}
}

// pickImage prefers the iTunes href (square cover art) over RSS's <url>.
func pickImage(i rssImage) string {
	if h := strings.TrimSpace(i.Href); h != "" {
		return h
	}
	return strings.TrimSpace(i.URL)
}

func atoiSafe(s string) int {
	n, err := strconv.Atoi(strings.TrimSpace(s))
	if err != nil || n < 0 {
		return 0
	}
	return n
}

func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		if strings.TrimSpace(v) != "" {
			return v
		}
	}
	return ""
}

// clean normalizes a text field for display: unescape entities the parser left
// (feeds double-escape constantly), drop any HTML, and collapse whitespace.
// Templates escape on output, so this is about legibility, not safety.
func clean(s string) string {
	s = html.UnescapeString(strings.TrimSpace(s))
	if strings.ContainsRune(s, '<') {
		s = stripTags(s)
	}
	return strings.Join(strings.Fields(s), " ")
}

// stripTags removes anything between angle brackets. Deliberately not an HTML
// parser: show notes are marketing HTML, not a document, and all we want is the
// prose. An unclosed '<' takes the rest of the string, which is the safe way to
// be wrong.
func stripTags(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	depth := 0
	for _, r := range s {
		switch {
		case r == '<':
			depth++
		case r == '>' && depth > 0:
			depth--
		case depth == 0:
			b.WriteRune(r)
		}
	}
	return b.String()
}
