package photoscan

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"sync"
	"time"

	"hespera/internal/video"
)

// Thumbnail + display-rendition generation. Grid thumbnails are generated by
// the photo_thumb job chained after every scan (missing-only — thumb_path=''
// marks a new/changed file); the larger display rendition (for formats a
// browser can't decode: HEIC/TIFF) is pre-generated by the same job and
// lazily backfilled on first view by the web layer via EnsureRendition. Both
// are id-keyed files under DataDir/thumbs/photos, deleted when their row
// prunes (and when their library is deleted — no scan runs after that).

const (
	thumbMaxDim     = 480
	renditionMaxDim = 2048
	// thumbUnavailable marks a file whose thumbnail generation failed (e.g. a
	// grid-HEIC this ffmpeg can't decode) so the job doesn't grind on it every
	// scan. Reset to '' (retried) when the file's bytes change. A transient
	// ffmpeg-gate acquire failure (video.ErrBusy) never writes this — the row
	// stays pending and the next thumb job retries it.
	thumbUnavailable = "unavailable"
)

// ThumbFileNames returns every generated file a photo id may own (thumb +
// rendition) — the prune pass and the library-delete path delete these.
func ThumbFileNames(id int64) []string {
	return []string{
		fmt.Sprintf("photo_%d.webp", id),
		fmt.Sprintf("photo_%d_full.webp", id),
	}
}

// BrowserDisplayable reports whether browsers render the still-image format
// natively — those serve the original file; the rest (HEIC/TIFF) get a webp
// rendition. Single source of truth: the web layer's full-size handler and
// the thumb job's eager rendition pass both key off it.
func BrowserDisplayable(container string) bool {
	switch container {
	case "jpg", "jpeg", "png", "gif", "webp", "avif", "bmp":
		return true
	default:
		return false
	}
}

func (s *Scanner) thumbsDir() string {
	return filepath.Join(s.Cfg.DataDir, "thumbs", "photos")
}

// GenerateThumbsMissing creates grid thumbnails for every row without one,
// plus the display rendition for formats a browser can't decode (so the
// viewer's first look is a cache hit, not a request-blocking encode).
// The reprobe shape: candidates only, near-free no-op when nothing is missing.
// Failures mark the row unavailable (placeholder in the grid) rather than
// erroring the job — one bad file must not starve the rest.
func (s *Scanner) GenerateThumbsMissing(ctx context.Context, jobID, libraryID int64) error {
	rows, err := s.DB.QueryContext(ctx,
		`SELECT id, abs_path, kind, container, orientation FROM photos WHERE library_id=? AND thumb_path=''`, libraryID)
	if err != nil {
		return err
	}
	type cand struct {
		id          int64
		absPath     string
		kind        string
		container   string
		orientation int
	}
	var cands []cand
	for rows.Next() {
		var c cand
		if err := rows.Scan(&c.id, &c.absPath, &c.kind, &c.container, &c.orientation); err != nil {
			rows.Close()
			return err
		}
		cands = append(cands, c)
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return err
	}
	if len(cands) == 0 {
		return nil
	}
	if err := os.MkdirAll(s.thumbsDir(), 0o755); err != nil {
		return err
	}
	sweepStaleTemps(s.thumbsDir())
	_, _ = s.DB.ExecContext(ctx, "UPDATE scan_jobs SET progress_total=? WHERE id=?", len(cands), jobID)

	for i, c := range cands {
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}
		dst := filepath.Join(s.thumbsDir(), ThumbFileNames(c.id)[0])
		mark := dst
		if err := video.PhotoThumb(ctx, c.absPath, dst, thumbMaxDim, c.orientation, c.kind == "video"); err != nil {
			if ctx.Err() != nil {
				return ctx.Err()
			}
			if errors.Is(err, video.ErrBusy) {
				// Gate saturation, not a broken file — leave thumb_path=''
				// so the next thumb job retries it.
				slog.Warn("photoscan thumb busy, will retry", "path", c.absPath, "err", err)
				continue
			}
			slog.Warn("photoscan thumb", "path", c.absPath, "err", err)
			mark = thumbUnavailable
		}
		if mark != thumbUnavailable && c.kind == "photo" && !BrowserDisplayable(c.container) {
			// Eager rendition: best-effort — the viewer's lazy path retries.
			if _, err := EnsureRendition(ctx, s.Cfg.DataDir, c.id, c.absPath, c.orientation); err != nil {
				slog.Warn("photoscan rendition", "path", c.absPath, "err", err)
			}
		}
		if _, err := s.DB.ExecContext(ctx, "UPDATE photos SET thumb_path=? WHERE id=?", mark, c.id); err != nil {
			return err
		}
		if (i+1)%25 == 0 || i+1 == len(cands) {
			_, _ = s.DB.ExecContext(ctx, "UPDATE scan_jobs SET progress_current=? WHERE id=?", i+1, jobID)
		}
	}
	return nil
}

// sweepStaleTemps removes temp files a hard-killed prior run left behind (the
// temp+rename pattern leaks its .tmp on SIGKILL). Age-gated well past the 60s
// per-encode ceiling so an in-flight build is never touched.
func sweepStaleTemps(dir string) {
	tmps, _ := filepath.Glob(filepath.Join(dir, "*.tmp"))
	for _, p := range tmps {
		if st, err := os.Stat(p); err == nil && time.Since(st.ModTime()) > time.Hour {
			_ = os.Remove(p)
		}
	}
}

// renditionLocks serialises EnsureRendition per photo id: two concurrent
// first-views must not run two ffmpeg encodes into the same temp/dst path —
// interleaved writes plus a mid-write rename would cache a corrupt rendition.
// Entries are one mutex per non-displayable photo ever viewed; never reaped,
// bounded by the library.
var renditionLocks sync.Map // photoID int64 -> *sync.Mutex

// EnsureRendition returns the path of a browser-displayable rendition for a
// photo whose native format the browser can't decode, generating and caching
// it on first request (the thumb job pre-generates it; this is the backfill).
// The caller decides *whether* a rendition is needed (browser-displayable
// formats serve the original). The scanner deletes the cached file when the
// source bytes change, so a hit here is never stale.
func EnsureRendition(ctx context.Context, dataDir string, photoID int64, absPath string, orientation int) (string, error) {
	dir := filepath.Join(dataDir, "thumbs", "photos")
	dst := filepath.Join(dir, ThumbFileNames(photoID)[1])
	mu, _ := renditionLocks.LoadOrStore(photoID, &sync.Mutex{})
	lock := mu.(*sync.Mutex)
	lock.Lock()
	defer lock.Unlock()
	if _, err := os.Stat(dst); err == nil {
		return dst, nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	if err := video.PhotoThumb(ctx, absPath, dst, renditionMaxDim, orientation, false); err != nil {
		return "", err
	}
	return dst, nil
}
