package main

// Ambient noise generation.
//
// This is a port of the brownnoise.sh that has been running on the upstairs Pi
// as a systemd unit (itself descended from a 2011 gist by Tom Swiss et al.).
// The shape of the sound is entirely SoX's: synthesize a short buffer of noise,
// band-pass it, modulate its volume very slowly so it breathes like surf, add a
// little reverb to smear the swell edges, then repeat the buffer. Pre-computing
// one buffer and repeating it is what keeps CPU near zero — the original's
// changelog claims 95%, and that property is preserved here.
//
// SoX rather than ffmpeg for the SHAPING, deliberately: ffmpeg's `tremolo`
// filter has a MINIMUM frequency of 0.1 Hz, and the swell that makes this
// pleasant runs at 0.08 Hz. The one characteristic worth keeping is the one
// ffmpeg cannot express. ffmpeg also has no equivalent of SoX's `reverb`.
//
// Three colours — blue, violet, velvet — do not exist in SoX at all, so those
// are GENERATED by ffmpeg's anoisesrc and piped into the same SoX chain. That
// is not a reversal of the above: the tremolo still runs in SoX, and ffmpeg
// only supplies raw noise. See noiseNeedsFFmpeg and runNoiseHybrid.
//
// Every parameter below is numeric or a whitelisted enum, and the argument
// vector is built directly (never a shell string), so no preset value can
// inject an argument however it was obtained.

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// noiseTypes are the colours a preset may name.
//
// The first four are SoX synth waveforms — the set the original script listed;
// tpdf is Triangular Probability Density Function, the dither noise. The last
// three do NOT exist in SoX at any version (verified: `sox -n synth 1 bluenoise`
// is rejected, and the manpage lists only the four). They exist in ffmpeg's
// anoisesrc, so a preset naming one is generated there and PIPED into SoX for
// the effect chain — see noiseNeedsFFmpeg.
//
// This is not a reversal of choosing SoX over ffmpeg. That decision turned on
// one property: the swell runs at 0.08 Hz and ffmpeg's `tremolo` filter has a
// minimum of 0.1 Hz. In the hybrid the tremolo still runs in SoX; ffmpeg only
// supplies raw noise, which it does for colours SoX cannot make at all.
var noiseTypes = []string{
	"whitenoise", "pinknoise", "brownnoise", "tpdfnoise", // SoX synth
	"bluenoise", "violetnoise", "velvetnoise", // ffmpeg anoisesrc only
}

// ffmpegColors maps a preset type to its anoisesrc colour name. A type absent
// here is synthesized by SoX directly.
var ffmpegColors = map[string]string{
	"bluenoise":   "blue",
	"violetnoise": "violet",
	"velvetnoise": "velvet",
}

// noiseNeedsFFmpeg reports whether this preset's colour has to be generated by
// ffmpeg and piped into SoX.
func (p noisePreset) noiseNeedsFFmpeg() bool {
	_, ok := ffmpegColors[p.Type]
	return ok
}

const (
	// noiseChannels matches the original's `-c 2`.
	noiseChannels = 2
	// noiseBuffer matches the original's `--buffer 131072` — 128 KB, which is
	// underrun protection on a small board.
	noiseBuffer = 131072

	// noiseSampleRate is what the ffmpeg generator produces. SoX's synth follows
	// the output device; anoisesrc needs telling.
	noiseSampleRate = 48000

	// noiseMinBufferSecs is the floor for the synthesized buffer. The original
	// used exactly 60s; we round UP from here to a whole number of swells.
	noiseMinBufferSecs = 60.0

	// noiseSafetyCapSecs bounds `repeat` so a hesplay that dies without reaping
	// its child cannot leave the box roaring indefinitely. It is NOT how a
	// session's length is controlled — the caller cancels the context for that,
	// which kills the process. Matches the original's effective 24h ceiling.
	noiseSafetyCapSecs = 24 * 60 * 60

	// noiseMaxWaveSpeed is the original's own advice, verbatim: "increase for
	// more volume oscillation, but suggest no higher than 0.20".
	noiseMaxWaveSpeed = 0.20
)

// noisePreset is one named noise configuration. Field names avoid the word
// "amplitude" on purpose: in the original it could mean either the depth of the
// volume swell or the output level, and they are different knobs.
type noisePreset struct {
	Name string `json:"name"`
	Type string `json:"type"` // one of noiseTypes

	CenterHz float64 `json:"centerHz"` // band-pass centre
	WidthHz  float64 `json:"widthHz"`  // band-pass width

	WaveSpeed float64 `json:"waveSpeed"` // tremolo Hz — one swell per 1/speed seconds
	WaveDepth float64 `json:"waveDepth"` // tremolo % — how deep the swell goes

	Reverb float64 `json:"reverb"` // SoX reverberance %
	GainDB float64 `json:"gainDb"` // output level; 0 = leave the level alone
	FadeIn float64 `json:"fadeIn"` // seconds; 0 = start at full level
}

// noiseConfig is the whole on-disk file. It lives on the BOX that makes the
// sound, not on the Hespera server, so a scheduled window still fires when the
// music server is unreachable.
type noiseConfig struct {
	// AudioDev is the ALSA device, e.g. "plughw:0". Empty lets SoX choose,
	// which is right on a desktop; a board with several cards wants it pinned
	// (the systemd unit this replaces pinned plughw:0).
	AudioDev string `json:"audioDev,omitempty"`
	// Default names the preset used when a caller doesn't name one.
	Default string `json:"default,omitempty"`
	// Presets are the named configurations.
	Presets []noisePreset `json:"presets"`
	// Schedule is read by the reconciler. Declared here so the file shape is
	// stable from the first release.
	Schedule []noiseWindow `json:"schedule,omitempty"`
}

// noiseWindow is one scheduled span. Times are local "HH:MM"; a window whose
// end is not after its start WRAPS MIDNIGHT, which is the normal case here
// (20:00→10:00 is 14 hours across a day boundary). Days holds time.Weekday
// values; empty means every day.
//
// The reconciler that consumes this lives in schedule.go; the type is declared
// beside the rest of the config so the on-disk shape is settled in one place.
type noiseWindow struct {
	Start  string `json:"start"`            // "HH:MM", local time
	End    string `json:"end"`              // "HH:MM", local time
	Days   []int  `json:"days,omitempty"`   // time.Weekday; empty = every day
	Preset string `json:"preset,omitempty"` // empty = the config default
}

// defaultNoiseConfig reproduces the shipped brownnoise command as the "brown"
// preset. Every other colour reuses the same effect chain and differs only in
// waveform and level: the original tuned that chain by ear for brown, and
// inventing per-colour band centres nobody has listened to would be fabricating
// a decision. They are starting points to tune, not recommendations.
//
// The gains are NOT a tuning judgement — they are measured. Run through the
// identical chain, the colours land far apart, because a band-pass at 1786 Hz
// takes a very different slice out of each spectrum:
//
//	brown -25.72 dB RMS   velvet -25.48   white -29.33
//	tpdf  -32.29          pink   -32.89   blue   -34.40   violet -46.27
//
// Shipping those unadjusted would mean switching from brown to violet sounded
// like the noise had stopped — a 20 dB drop. Each gain brings its colour up to
// brown's measured level, leaving brown itself at 0 so the reference stays
// byte-identical to the original command.
//
// Caveat worth knowing before trusting them: equal RMS is not equal LOUDNESS.
// The ear is most sensitive around 2-4 kHz, so the high-frequency colours (blue,
// violet) will still read as somewhat louder than brown at matched RMS. These
// are a sane starting point, not a psychoacoustic match — trim by ear with the
// gain knob, which is exactly what it is for.
func defaultNoiseConfig() noiseConfig {
	base := func(name, typ string, gain float64) noisePreset {
		return noisePreset{
			Name: name, Type: typ,
			CenterHz: 1786, WidthHz: 499,
			WaveSpeed: 0.08, WaveDepth: 37,
			Reverb: 19, GainDB: gain, FadeIn: 3,
		}
	}
	return noiseConfig{
		Default: "brown",
		Presets: []noisePreset{
			base("brown", "brownnoise", 0), // the reference: unchanged from the original
			base("pink", "pinknoise", 7),
			base("white", "whitenoise", 3.5),
			base("tpdf", "tpdfnoise", 6.5),
			// Generated by ffmpeg and piped into SoX — no SoX version can make
			// these. Violet wants +20.55 to match brown but the gain clamp is
			// +20, so it lands about half a dB shy; that is the clamp doing its
			// job, not a miscalculation.
			base("blue", "bluenoise", 8.5),
			base("violet", "violetnoise", 20),
			base("velvet", "velvetnoise", 0),
		},
	}
}

// noiseConfigPath sits beside the saved server file, under the same per-user
// config dir. Deliberately a SEPARATE file from hesplay-server: that one is
// read by every hesplay invocation including one-shot verbs, and this feature
// has no business touching that path.
func noiseConfigPath() (string, error) {
	dir, err := os.UserConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "hespera", "hesplay.json"), nil
}

// loadNoiseConfig reads the config, falling back to the built-in defaults when
// there is no file yet. A file that exists but is corrupt is an error rather
// than a silent reset — silently replacing a tuned preset set would be worse
// than refusing to start.
func loadNoiseConfig() (noiseConfig, error) {
	p, err := noiseConfigPath()
	if err != nil {
		return defaultNoiseConfig(), nil
	}
	b, err := os.ReadFile(p)
	if errors.Is(err, os.ErrNotExist) {
		return defaultNoiseConfig(), nil
	}
	if err != nil {
		return noiseConfig{}, err
	}
	var cfg noiseConfig
	if err := json.Unmarshal(b, &cfg); err != nil {
		return noiseConfig{}, fmt.Errorf("%s: %w", p, err)
	}
	if len(cfg.Presets) == 0 {
		cfg.Presets = defaultNoiseConfig().Presets
	}
	return cfg, nil
}

// saveNoiseConfig writes the config atomically — temp file then rename — so an
// interrupted write cannot leave the box with a half-parsed schedule.
func saveNoiseConfig(cfg noiseConfig) error {
	p, err := noiseConfigPath()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return err
	}
	b, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(p), ".hesplay-*.json")
	if err != nil {
		return err
	}
	name := tmp.Name()
	defer os.Remove(name) // no-op once the rename below succeeds
	if _, err := tmp.Write(append(b, '\n')); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(name, 0o644); err != nil {
		return err
	}
	return os.Rename(name, p)
}

// findPreset resolves a preset by name, case-insensitively, falling back to the
// configured default when the name is empty.
func (cfg noiseConfig) findPreset(name string) (noisePreset, error) {
	name = strings.TrimSpace(name)
	if name == "" {
		name = cfg.Default
	}
	if name == "" && len(cfg.Presets) > 0 {
		return cfg.Presets[0], nil
	}
	for _, p := range cfg.Presets {
		if strings.EqualFold(p.Name, name) {
			return p, nil
		}
	}
	names := make([]string, 0, len(cfg.Presets))
	for _, p := range cfg.Presets {
		names = append(names, p.Name)
	}
	return noisePreset{}, fmt.Errorf("no noise preset %q (have: %s)", name, strings.Join(names, ", "))
}

// normalize clamps every field into a range SoX will accept and a human will
// tolerate, and fills a usable default for anything left at zero. It never
// returns an error for an out-of-range number: a preset edited to something
// silly should still make noise, just sane noise. An unknown TYPE is the one
// exception, because there is no sensible clamp for a waveform name.
func (p noisePreset) normalize() (noisePreset, error) {
	out := p
	out.Type = strings.ToLower(strings.TrimSpace(out.Type))
	if out.Type == "" {
		out.Type = "brownnoise"
	}
	// Accept the bare colour ("brown") as well as SoX's name ("brownnoise"),
	// since the original script's variable held the bare form.
	if !strings.HasSuffix(out.Type, "noise") {
		out.Type += "noise"
	}
	if !knownNoiseType(out.Type) {
		return noisePreset{}, fmt.Errorf("unknown noise type %q (have: %s)", p.Type, strings.Join(noiseTypes, ", "))
	}

	out.CenterHz = clampFloat(out.CenterHz, 20, 20000, 1786)
	out.WidthHz = clampFloat(out.WidthHz, 1, 20000, 499)
	out.WaveSpeed = clampFloat(out.WaveSpeed, 0.001, noiseMaxWaveSpeed, 0.08)
	out.WaveDepth = clampFloat(out.WaveDepth, 0, 100, 37)
	out.Reverb = clampFloat(out.Reverb, 0, 100, 19)
	out.FadeIn = clampFloat(out.FadeIn, 0, 300, 0)
	// Gain's zero value is meaningful (leave the level alone), so it is clamped
	// but never defaulted.
	out.GainDB = math.Max(-60, math.Min(20, out.GainDB))
	return out, nil
}

func knownNoiseType(t string) bool {
	for _, k := range noiseTypes {
		if k == t {
			return true
		}
	}
	return false
}

// clampFloat bounds v into [lo,hi], substituting def for a non-positive or
// non-finite value so a zeroed JSON field lands on something usable.
func clampFloat(v, lo, hi, def float64) float64 {
	if math.IsNaN(v) || math.IsInf(v, 0) || v <= 0 {
		v = def
	}
	return math.Max(lo, math.Min(hi, v))
}

// bufferSecs is the length of the synthesized buffer that gets repeated.
//
// It is DERIVED, never configured, and that is the whole point. The original
// hardcoded a 60s buffer while running the swell at 0.08 Hz — a 12.5s period —
// which is 4.8 swells per buffer, so the volume envelope jumped mid-swell at
// every loop point. Rounding up to a whole number of swells makes the loop
// seamless without changing the sound at all. A knob here could only ever be
// set to a value that seams.
func (p noisePreset) bufferSecs() float64 {
	period := 1 / p.WaveSpeed
	n := math.Ceil(noiseMinBufferSecs / period)
	if n < 1 {
		n = 1
	}
	return n * period
}

// repeatCount is the `repeat` argument: how many EXTRA times the buffer plays
// after the first. Sized to the safety cap, not to the session length — see
// noiseSafetyCapSecs.
func (p noisePreset) repeatCount() int {
	n := int(math.Ceil(noiseSafetyCapSecs/p.bufferSecs())) - 1
	if n < 0 {
		n = 0
	}
	return n
}

// noiseArgs builds the `play` argument vector.
//
// Effect ORDER is load-bearing. `repeat` replays everything before it in the
// chain, so `gain` and `fade` must come AFTER it: a fade placed before the
// repeat would re-fade on every single loop iteration, turning a one-time
// ease-in into a pulse every buffer length.
func (p noisePreset) noiseArgs() []string {
	if p.noiseNeedsFFmpeg() {
		return p.soxPipeArgs()
	}
	a := []string{
		"--buffer", strconv.Itoa(noiseBuffer),
		"--no-show-progress",
		"-c", strconv.Itoa(noiseChannels),
		"--null",
		"synth", num(p.bufferSecs()), p.Type,
	}
	a = append(a, p.shapeArgs()...)
	// repeat sits between the shaping and the level/fade for the same reason the
	// comment above gives: everything BEFORE it is what gets replayed.
	a = append(a, "repeat", strconv.Itoa(p.repeatCount()))
	return append(a, p.finishArgs()...)
}

// shapeArgs is the timbre: band-pass, the slow swell, and reverb. Identical on
// both paths, so a hybrid colour is shaped by exactly the chain that was tuned
// by ear for brown.
func (p noisePreset) shapeArgs() []string {
	return []string{
		"band", "-n", num(p.CenterHz), num(p.WidthHz),
		"tremolo", num(p.WaveSpeed), num(p.WaveDepth),
		"reverb", num(p.Reverb),
	}
}

// finishArgs is level then fade — always last, and on the native path always
// after `repeat`.
func (p noisePreset) finishArgs() []string {
	var a []string
	if p.GainDB != 0 {
		a = append(a, "gain", num(p.GainDB))
	}
	if p.FadeIn > 0 {
		a = append(a, "fade", "t", num(p.FadeIn))
	}
	return a
}

// soxPipeArgs is the SoX side of the hybrid: read the generated stream from
// stdin and shape it.
//
// There is deliberately no `synth` and no `repeat`. ffmpeg generates
// continuously, so there is no buffer to loop — which also means the hybrid
// path has no loop seam to fix, and `repeat` would be actively wrong here
// (SoX's repeat buffers its input to replay it, and this input never ends).
// Nor `-c 2`: on the native path that describes the null input device, but here
// the channel count comes from the piped WAV header.
func (p noisePreset) soxPipeArgs() []string {
	a := []string{
		"--buffer", strconv.Itoa(noiseBuffer),
		"--no-show-progress",
		"-t", "wav", "-",
	}
	a = append(a, p.shapeArgs()...)
	return append(a, p.finishArgs()...)
}

// ffmpegArgs is the generator side of the hybrid. -t caps it at the same 24h
// safety ceiling `repeat` gives the native path, for the same reason: a hesplay
// that dies without reaping its children must not leave the box roaring.
func (p noisePreset) ffmpegArgs() []string {
	return []string{
		"-hide_banner", "-loglevel", "error",
		"-f", "lavfi",
		"-i", fmt.Sprintf("anoisesrc=color=%s:r=%d:d=%d", ffmpegColors[p.Type], noiseSampleRate, noiseSafetyCapSecs),
		// anoisesrc is mono; the native path plays two channels, so match it.
		"-ac", strconv.Itoa(noiseChannels),
		"-f", "wav", "-",
	}
}

// num formats a float the way a person would write it: no trailing zeros, no
// exponent. SoX parses these as plain seconds/Hz/percent.
func num(f float64) string {
	return strconv.FormatFloat(f, 'f', -1, 64)
}

// noisePlayer is the SoX playback binary. `play` is SoX's playback front-end;
// it is what the original script used and what both target boxes have.
type noisePlayer struct{ path string }

func findNoisePlayer() (noisePlayer, error) {
	p, err := exec.LookPath("play")
	if err != nil {
		return noisePlayer{}, errors.New("no noise engine: install sox (provides `play`)")
	}
	return noisePlayer{path: p}, nil
}

// noiseGenerator is ffmpeg, needed only by the colours SoX cannot synthesize.
type noiseGenerator struct{ path string }

func findNoiseGenerator() (noiseGenerator, error) {
	p, err := exec.LookPath("ffmpeg")
	if err != nil {
		return noiseGenerator{}, errors.New("blue, violet and velvet noise are generated by ffmpeg, which is not installed (the other colours need only sox)")
	}
	return noiseGenerator{path: p}, nil
}

// noiseEnv is the environment for the play process. The original systemd unit
// set AUDIODRIVER=alsa and AUDIODEV=plughw:0 to pin the output; carrying that
// through config matters because SoX's default device need not be the one mpv
// picks, and a wrong-sink failure is silent.
func noiseEnv(audioDev string) []string {
	env := os.Environ()
	if d := strings.TrimSpace(audioDev); d != "" {
		env = append(env, "AUDIODRIVER=alsa", "AUDIODEV="+d)
	}
	return env
}

// runNoise plays one preset until the context is cancelled or the safety cap
// runs out. Cancelling kills the process — that is how a session ends, and why
// `repeat` is only a backstop rather than the timer.
//
// onStart (may be nil) receives the PLAYER process once it is running — the one
// that owns the audio device — which is what the remote's pause signals. It is
// a callback rather than a return value because this function blocks for the
// whole session.
//
// There is no stall guard here, unlike the music engine: SoX exposes no IPC
// socket, so a process that is alive but silent cannot be distinguished from
// one that is working. A process that EXITS is detectable and the caller
// restarts it; a wedged one is a known, accepted gap.
func runNoise(ctx context.Context, pl noisePlayer, p noisePreset, audioDev string, onStart func(*os.Process)) error {
	if p.noiseNeedsFFmpeg() {
		return runNoiseHybrid(ctx, pl, p, audioDev, onStart)
	}
	cmd := exec.CommandContext(ctx, pl.path, p.noiseArgs()...)
	cmd.Env = noiseEnv(audioDev)
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("%s: %w", filepath.Base(pl.path), err)
	}
	if onStart != nil {
		onStart(cmd.Process)
	}
	if err := cmd.Wait(); err != nil {
		if ctx.Err() != nil {
			return nil // cancelled: the intended way to stop
		}
		return fmt.Errorf("%s: %w", filepath.Base(pl.path), err)
	}
	return nil
}

// runNoiseHybrid generates with ffmpeg and shapes with SoX, for the colours SoX
// cannot synthesize.
//
// A real OS pipe rather than StdoutPipe/io.Copy, and both ends closed in the
// parent once the children hold them. That matters for shutdown: with the write
// end held open here, SoX would never see EOF, and with the read end held open
// ffmpeg would never get EPIPE. Closed, the pair tears itself down — if the
// player exits first, the generator dies of a broken pipe on its next write
// instead of lingering as an orphan writing into nothing.
func runNoiseHybrid(ctx context.Context, pl noisePlayer, p noisePreset, audioDev string, onStart func(*os.Process)) error {
	ff, err := findNoiseGenerator()
	if err != nil {
		return err
	}

	gen := exec.CommandContext(ctx, ff.path, p.ffmpegArgs()...)
	shape := exec.CommandContext(ctx, pl.path, p.soxPipeArgs()...)
	shape.Env = noiseEnv(audioDev)

	pr, pw, err := os.Pipe()
	if err != nil {
		return err
	}
	gen.Stdout, gen.Stderr = pw, os.Stderr
	shape.Stdin = pr
	shape.Stdout, shape.Stderr = os.Stdout, os.Stderr

	if err := gen.Start(); err != nil {
		pr.Close()
		pw.Close()
		return fmt.Errorf("%s: %w", filepath.Base(ff.path), err)
	}
	if err := shape.Start(); err != nil {
		pr.Close()
		pw.Close()
		_ = gen.Process.Kill()
		_ = gen.Wait()
		return fmt.Errorf("%s: %w", filepath.Base(pl.path), err)
	}
	pr.Close()
	pw.Close()
	if onStart != nil {
		onStart(shape.Process) // the player, not the generator: pause freezes the device owner
	}

	// Wait on the PLAYER, because it owns the audio device and its exit is what
	// "the noise stopped" means. Then make sure the generator is gone rather
	// than assuming EPIPE got there first — an orphaned ffmpeg would hold no
	// device but would burn CPU forever.
	werr := shape.Wait()
	if gen.Process != nil {
		_ = gen.Process.Kill()
	}
	_ = gen.Wait()

	if werr != nil && ctx.Err() == nil {
		return fmt.Errorf("%s: %w", filepath.Base(pl.path), werr)
	}
	return nil
}

// cmdNoise is the `noise` verb: play a preset, list them, or print the exact
// SoX invocation without running it.
//
//	hesplay noise                 play the default preset until Ctrl+C
//	hesplay noise brown           play a named preset
//	hesplay noise --for 45 brown  stop after 45 minutes
//	hesplay noise list            list the presets
//	hesplay noise --print brown   print the command, play nothing
//
// Arguments are scanned rather than passed to a FlagSet so a flag may sit
// anywhere, matching the rest of hesplay where a bare name needs no quoting.
func cmdNoise(ctx context.Context, args []string) error {
	var (
		printOnly bool
		list      bool
		minutes   float64
		words     []string
	)
	for i := 0; i < len(args); i++ {
		a := args[i]
		switch {
		case isHelp(a):
			usage()
			return nil
		case a == "--print" || a == "--print-command":
			printOnly = true
		case a == "list":
			list = true
		case a == "--for" || a == "-for":
			if i+1 >= len(args) {
				return errors.New("--for: expected a number of minutes")
			}
			i++
			m, err := strconv.ParseFloat(args[i], 64)
			if err != nil || m <= 0 {
				return fmt.Errorf("--for: %q is not a positive number of minutes", args[i])
			}
			minutes = m
		case strings.HasPrefix(a, "--for="):
			m, err := strconv.ParseFloat(strings.TrimPrefix(a, "--for="), 64)
			if err != nil || m <= 0 {
				return fmt.Errorf("--for: %q is not a positive number of minutes", a)
			}
			minutes = m
		default:
			words = append(words, a)
		}
	}

	cfg, err := loadNoiseConfig()
	if err != nil {
		return err
	}
	if list {
		return listNoisePresets(cfg)
	}

	preset, err := cfg.findPreset(strings.Join(words, " "))
	if err != nil {
		return err
	}
	preset, err = preset.normalize()
	if err != nil {
		return err
	}

	pl, err := findNoisePlayer()
	if err != nil {
		return err
	}
	if printOnly {
		fmt.Println(noiseCommandLine(pl, preset, cfg.AudioDev))
		return nil
	}

	if minutes > 0 {
		fmt.Printf("%s noise for %g minutes (Ctrl+C to stop)\n", preset.Name, minutes)
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, time.Duration(minutes*float64(time.Minute)))
		defer cancel()
	} else {
		fmt.Printf("%s noise (Ctrl+C to stop)\n", preset.Name)
	}
	return runNoise(ctx, pl, preset, cfg.AudioDev, nil)
}

// listNoisePresets prints the configured presets, marking the default. The
// swell period is shown derived rather than raw because "one swell every 12.5s"
// is the thing a person is actually choosing.
func listNoisePresets(cfg noiseConfig) error {
	tw := newTable("NAME", "TYPE", "BAND", "SWELL", "DEPTH", "REVERB", "GAIN")
	for _, p := range cfg.Presets {
		n, err := p.normalize()
		if err != nil {
			return err
		}
		name := n.Name
		if strings.EqualFold(name, cfg.Default) {
			name += " *"
		}
		fmt.Fprintf(tw, "%s\t%s\t%g±%g Hz\t%.1fs\t%g%%\t%g%%\t%+g dB\n",
			name, strings.TrimSuffix(n.Type, "noise"),
			n.CenterHz, n.WidthHz, 1/n.WaveSpeed, n.WaveDepth, n.Reverb, n.GainDB)
	}
	return tw.Flush()
}

// noiseCommandLine renders the invocation for --print-command and for tests.
// Quoting is display-only: the real call passes the vector to exec, so nothing
// here is ever parsed by a shell.
func noiseCommandLine(pl noisePlayer, p noisePreset, audioDev string) string {
	var b strings.Builder
	// The hybrid colours render as the pipeline they actually are, so what is
	// printed can be pasted into a shell and reproduce exactly what plays.
	if p.noiseNeedsFFmpeg() {
		gen := "ffmpeg"
		if g, err := findNoiseGenerator(); err == nil {
			gen = filepath.Base(g.path)
		}
		writeCmd(&b, gen, p.ffmpegArgs())
		b.WriteString(" | ")
	}
	if d := strings.TrimSpace(audioDev); d != "" {
		b.WriteString("AUDIODRIVER=alsa AUDIODEV=" + d + " ")
	}
	writeCmd(&b, filepath.Base(pl.path), p.noiseArgs())
	return b.String()
}

// writeCmd appends `name arg arg …`, quoting only what a shell would need
// quoted. Display-only: the real calls pass vectors to exec, so nothing here is
// ever parsed by a shell.
func writeCmd(b *strings.Builder, name string, args []string) {
	b.WriteString(name)
	for _, a := range args {
		b.WriteString(" ")
		if a == "" || strings.ContainsAny(a, " \t|&;<>()$`\\\"'") {
			b.WriteString(strconv.Quote(a))
			continue
		}
		b.WriteString(a)
	}
}
