package main

// Ambient noise generation.
//
// This is a port of the brownnoise.sh that has been running on the upstairs Pi
// as a systemd unit (itself descended from a 2011 gist by Tom Swiss et al.).
// The shape of the sound is entirely SoX's: synthesize a short buffer of noise,
// band-pass it, modulate its volume very slowly so it breathes like surf, add a
// little reverb to smear the swell edges, then repeat the buffer. Pre-computing
// one buffer and repeating it is what keeps CPU near zero — the original's
// changelog claims 95%, and that property is preserved here.
//
// SoX rather than ffmpeg for the SHAPING, deliberately: ffmpeg's `tremolo`
// filter has a MINIMUM frequency of 0.1 Hz, and the swell that makes this
// pleasant runs at 0.08 Hz. The one characteristic worth keeping is the one
// ffmpeg cannot express. ffmpeg also has no equivalent of SoX's `reverb`.
//
// Three colours — blue, violet, velvet — do not exist in SoX at all, so those
// are GENERATED by ffmpeg's anoisesrc and piped into the same SoX chain. That
// is not a reversal of the above: the tremolo still runs in SoX, and ffmpeg
// only supplies raw noise. See noiseNeedsFFmpeg and runNoiseHybrid.
//
// Every parameter below is numeric or a whitelisted enum, and the argument
// vector is built directly (never a shell string), so no preset value can
// inject an argument however it was obtained.

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// noiseTypes are the colours a preset may name.
//
// The first four are SoX synth waveforms — the set the original script listed;
// tpdf is Triangular Probability Density Function, the dither noise. The last
// three do NOT exist in SoX at any version (verified: `sox -n synth 1 bluenoise`
// is rejected, and the manpage lists only the four). They exist in ffmpeg's
// anoisesrc, so a preset naming one is generated there and PIPED into SoX for
// the effect chain — see noiseNeedsFFmpeg.
//
// This is not a reversal of choosing SoX over ffmpeg. That decision turned on
// one property: the swell runs at 0.08 Hz and ffmpeg's `tremolo` filter has a
// minimum of 0.1 Hz. In the hybrid the tremolo still runs in SoX; ffmpeg only
// supplies raw noise, which it does for colours SoX cannot make at all.
var noiseTypes = []string{
	"whitenoise", "pinknoise", "brownnoise", "tpdfnoise", // SoX synth
	"bluenoise", "violetnoise", "velvetnoise", // ffmpeg anoisesrc only
}

// ffmpegColors maps a preset type to its anoisesrc colour name. A type absent
// here is synthesized by SoX directly.
var ffmpegColors = map[string]string{
	"bluenoise":   "blue",
	"violetnoise": "violet",
	"velvetnoise": "velvet",
}

// noiseNeedsFFmpeg reports whether this preset's colour has to be generated by
// ffmpeg and piped into SoX.
func (p noisePreset) noiseNeedsFFmpeg() bool {
	_, ok := ffmpegColors[p.Type]
	return ok
}

// floorActive reports whether this preset carries the third, floor layer —
// which switches playback to the mixed multi-process topology (runNoiseFloor).
func (p noisePreset) floorActive() bool { return p.FloorType != "" }

func (p noisePreset) floorNeedsFFmpeg() bool {
	_, ok := ffmpegColors[p.FloorType]
	return ok
}

const (
	// noiseChannels matches the original's `-c 2`.
	noiseChannels = 2
	// noiseBuffer matches the original's `--buffer 131072` — 128 KB, which is
	// underrun protection on a small board.
	noiseBuffer = 131072

	// noiseSampleRate is what the ffmpeg generator produces. SoX's synth follows
	// the output device; anoisesrc needs telling.
	noiseSampleRate = 48000

	// noiseMinBufferSecs is the floor for the synthesized buffer. The original
	// used exactly 60s; we round UP from here to a whole number of swells.
	noiseMinBufferSecs = 60.0

	// noiseSafetyCapSecs bounds `repeat` so a hesplay that dies without reaping
	// its child cannot leave the box roaring indefinitely. It is NOT how a
	// session's length is controlled — the caller cancels the context for that,
	// which kills the process. Matches the original's effective 24h ceiling.
	noiseSafetyCapSecs = 24 * 60 * 60

	// noiseMaxWaveSpeed is the original's own advice, verbatim: "increase for
	// more volume oscillation, but suggest no higher than 0.20".
	noiseMaxWaveSpeed = 0.20

	// noiseMaxBufferSecs caps the two-swell buffer derivation. `repeat` buffers
	// its whole input in memory, so an incommensurate pair of swell rates must
	// not be allowed to demand an hour-long buffer hunting for a common period —
	// past this cap the derivation settles for seaming the faster swell instead
	// (see commensurateBufferSecs). 300s ≈ 115 MB at 48k stereo 32-bit.
	noiseMaxBufferSecs = 300.0
)

// noisePreset is one named noise configuration. Field names avoid the word
// "amplitude" on purpose: in the original it could mean either the depth of the
// volume swell or the output level, and they are different knobs.
type noisePreset struct {
	Name string `json:"name"`
	Type string `json:"type"` // one of noiseTypes

	CenterHz float64 `json:"centerHz"` // band-pass centre
	WidthHz  float64 `json:"widthHz"`  // band-pass width

	WaveSpeed float64 `json:"waveSpeed"` // tremolo Hz — one swell per 1/speed seconds
	WaveDepth float64 `json:"waveDepth"` // tremolo % — how deep the swell goes

	Reverb float64 `json:"reverb"` // SoX reverberance %
	GainDB float64 `json:"gainDb"` // output level; 0 = leave the level alone
	FadeIn float64 `json:"fadeIn"` // seconds; 0 = start at full level

	// A second, much slower swell layered under the first — "a small wave
	// receding as a larger wave comes in" (Dan, 2026-08-07): the single
	// seamless-looping tremolo the port perfected turned out to be TOO perfect,
	// a metronomic 12.5s swell forever (the original's 60s buffer held 4.8
	// swells, so its envelope jumped phase every minute — accidental
	// irregularity the seam fix deleted). Wave2Speed 0 = off, and every
	// existing preset stays byte-identical in argv.
	//
	// Two flavours. Wave2Type empty: the second swell is a second tremolo on
	// the SAME stream — chained tremolos multiply their envelopes, so the slow
	// one is the tide the fast waves ride. Wave2Type set to a SoX-native
	// colour: the slow swell is carried by ITS OWN noise layer, synthesized
	// first, enveloped alone, then the base colour mixes in un-swelled
	// underneath — verified numerically (windowed RMS held −11 dB through a
	// 100%-depth trough that took a single stream to −65 dB), so the bed
	// genuinely persists while the big wave comes and goes.
	Wave2Speed float64 `json:"wave2Speed,omitempty"` // slow-swell tremolo Hz; 0 = single swell
	Wave2Depth float64 `json:"wave2Depth,omitempty"` // slow-swell depth %
	Wave2Type  string  `json:"wave2Type,omitempty"`  // optional SoX colour carrying the slow swell; "" = same stream
	Wave2Gain  float64 `json:"wave2Gain,omitempty"`  // level trim on that layer, dB; 0 = none
	// Wave2Offset de-synchronizes the two swells (Dan: "all the noises
	// slightly offset from one another") — with both tremolos starting at
	// their peak, the tide crest always lands ON a wave crest. SoX's tremolo
	// has no phase argument, so the offset is a `trim` placed AFTER one
	// envelope and before the other: trim discards the head of the stream,
	// which shifts every effect upstream of it by that many seconds relative
	// to everything downstream (verified: a 2.5s trim moved the measured
	// trough by exactly 2.5s, and the loop seam stays phase-continuous
	// because the synth runs OFFSET seconds long and repeat loops the
	// post-trim whole-period remainder).
	Wave2Offset float64 `json:"wave2Offset,omitempty"` // seconds; shifts the fast swell against the slow one

	// The floor (2026-08-07, tuned by ear with Dan): a third layer far
	// underneath the sea — its own colour, its own bright band, its own
	// barely-there swell. It cannot ride the body's effect chain (everything
	// mixed in mid-chain shares all downstream effects — the body's band would
	// erase a 4.5 kHz floor entirely), so a floor preset runs as its own SoX
	// stage mixed with the body by `play -m` at unity; that also lets the
	// floor be an ffmpeg-only colour like velvet, which no mid-chain `synth`
	// could make. FloorType empty = no floor, and the whole topology (and
	// every existing preset's argv) is unchanged.
	FloorType     string  `json:"floorType,omitempty"`     // any colour; "" = no floor
	FloorCenterHz float64 `json:"floorCenterHz,omitempty"` // its own band centre (bright)
	FloorWidthHz  float64 `json:"floorWidthHz,omitempty"`  // its own band width
	FloorSpeed    float64 `json:"floorSpeed,omitempty"`    // its swell Hz; 0 = perfectly still
	FloorDepth    float64 `json:"floorDepth,omitempty"`    // its swell depth %
	FloorGain     float64 `json:"floorGain,omitempty"`     // dB; strongly negative = "underneath"
	FloorOffset   float64 `json:"floorOffset,omitempty"`   // seconds; shifts the floor's breath against the body's tide
}

// noiseConfig is the whole on-disk file. It lives on the BOX that makes the
// sound, not on the Hespera server, so a scheduled window still fires when the
// music server is unreachable.
type noiseConfig struct {
	// AudioDev is the ALSA device, e.g. "plughw:0". Empty lets SoX choose,
	// which is right on a desktop; a board with several cards wants it pinned
	// (the systemd unit this replaces pinned plughw:0).
	AudioDev string `json:"audioDev,omitempty"`
	// Default names the preset used when a caller doesn't name one.
	Default string `json:"default,omitempty"`
	// Presets are the named configurations.
	Presets []noisePreset `json:"presets"`
	// Schedule is read by the reconciler. Declared here so the file shape is
	// stable from the first release.
	Schedule []noiseWindow `json:"schedule,omitempty"`
}

// noiseWindow is one scheduled span. Times are local "HH:MM"; a window whose
// end is not after its start WRAPS MIDNIGHT, which is the normal case here
// (20:00→10:00 is 14 hours across a day boundary). Days holds time.Weekday
// values; empty means every day.
//
// The reconciler that consumes this lives in schedule.go; the type is declared
// beside the rest of the config so the on-disk shape is settled in one place.
type noiseWindow struct {
	Start  string `json:"start"`            // "HH:MM", local time
	End    string `json:"end"`              // "HH:MM", local time
	Days   []int  `json:"days,omitempty"`   // time.Weekday; empty = every day
	Preset string `json:"preset,omitempty"` // empty = the config default
}

// defaultNoiseConfig reproduces the shipped brownnoise command as the "brown"
// preset. Every other colour reuses the same effect chain and differs only in
// waveform and level: the original tuned that chain by ear for brown, and
// inventing per-colour band centres nobody has listened to would be fabricating
// a decision. They are starting points to tune, not recommendations.
//
// The gains are NOT a tuning judgement — they are measured. Run through the
// identical chain, the colours land far apart, because a band-pass at 1786 Hz
// takes a very different slice out of each spectrum:
//
//	brown -25.72 dB RMS   velvet -25.48   white -29.33
//	tpdf  -32.29          pink   -32.89   blue   -34.40   violet -46.27
//
// Shipping those unadjusted would mean switching from brown to violet sounded
// like the noise had stopped — a 20 dB drop. Each gain brings its colour up to
// brown's measured level, leaving brown itself at 0 so the reference stays
// byte-identical to the original command.
//
// Caveat worth knowing before trusting them: equal RMS is not equal LOUDNESS.
// The ear is most sensitive around 2-4 kHz, so the high-frequency colours (blue,
// violet) will still read as somewhat louder than brown at matched RMS. These
// are a sane starting point, not a psychoacoustic match — trim by ear with the
// gain knob, which is exactly what it is for.
func defaultNoiseConfig() noiseConfig {
	base := func(name, typ string, gain float64) noisePreset {
		return noisePreset{
			Name: name, Type: typ,
			CenterHz: 1786, WidthHz: 499,
			WaveSpeed: 0.08, WaveDepth: 37,
			Reverb: 19, GainDB: gain, FadeIn: 3,
		}
	}
	return noiseConfig{
		Default: "brown",
		Presets: []noisePreset{
			base("brown", "brownnoise", 0), // the reference: unchanged from the original
			base("pink", "pinknoise", 7),
			base("white", "whitenoise", 3.5),
			base("tpdf", "tpdfnoise", 6.5),
			// Generated by ffmpeg and piped into SoX — no SoX version can make
			// these. Violet wants +20.55 to match brown but the gain clamp is
			// +20, so it lands about half a dB shy; that is the clamp doing its
			// job, not a miscalculation.
			base("blue", "bluenoise", 8.5),
			base("violet", "violetnoise", 20),
			base("velvet", "velvetnoise", 0),
			// The ocean pair, tuned by ear with Dan on danlap (2026-08-07): a
			// 50s deep swell under the classic 12.5s one — a small wave
			// receding as a larger wave comes in — over a bright velvet floor
			// that barely breathes. "ocean brown" chains both swells on the
			// one brown stream; "ocean pink" swaps the roles — a pink bed of
			// small waves with the big slow wave a separate BROWN layer over
			// it (brown layer −7 plus overall +7 keeps the pair level-matched
			// at brown's reference loudness, mirroring pink's measured +7).
			oceanFloor(noisePreset{Name: "ocean brown", Type: "brownnoise",
				CenterHz: 1786, WidthHz: 499, WaveSpeed: 0.08, WaveDepth: 37,
				Wave2Speed: 0.02, Wave2Depth: 45, Wave2Offset: 6.25, Reverb: 19, FadeIn: 3}),
			oceanFloor(noisePreset{Name: "ocean pink", Type: "pinknoise",
				CenterHz: 1786, WidthHz: 499, WaveSpeed: 0.08, WaveDepth: 37,
				Wave2Type: "brownnoise", Wave2Gain: -7, Wave2Speed: 0.02, Wave2Depth: 45, Wave2Offset: 6.25,
				GainDB: 7, Reverb: 19, FadeIn: 3}),
		},
	}
}

// oceanFloor adds the velvet floor both ocean presets share — bright (banded
// at 4.5 kHz), tide-synced but barely moving (depth 18 ≈ a 2 dB breath), far
// underneath (−30 dB). Every number here was walked in by ear with Dan
// (2026-08-07: −6 "way too loud" → −18 "still too loud" → −26 → −30 with
// depth 60 → 18 "barely move, not enough to disappear").
func oceanFloor(p noisePreset) noisePreset {
	p.FloorType = "velvetnoise"
	p.FloorCenterHz, p.FloorWidthHz = 4500, 2000
	p.FloorSpeed, p.FloorDepth = 0.02, 18
	p.FloorGain = -30
	p.FloorOffset = 12.5
	return p
}

// noiseConfigPath sits beside the saved server file, under the same per-user
// config dir. Deliberately a SEPARATE file from hesplay-server: that one is
// read by every hesplay invocation including one-shot verbs, and this feature
// has no business touching that path.
func noiseConfigPath() (string, error) {
	dir, err := os.UserConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "hespera", "hesplay.json"), nil
}

// loadNoiseConfig reads the config, falling back to the built-in defaults when
// there is no file yet. A file that exists but is corrupt is an error rather
// than a silent reset — silently replacing a tuned preset set would be worse
// than refusing to start.
func loadNoiseConfig() (noiseConfig, error) {
	p, err := noiseConfigPath()
	if err != nil {
		return defaultNoiseConfig(), nil
	}
	b, err := os.ReadFile(p)
	if errors.Is(err, os.ErrNotExist) {
		return defaultNoiseConfig(), nil
	}
	if err != nil {
		return noiseConfig{}, err
	}
	var cfg noiseConfig
	if err := json.Unmarshal(b, &cfg); err != nil {
		return noiseConfig{}, fmt.Errorf("%s: %w", p, err)
	}
	if len(cfg.Presets) == 0 {
		cfg.Presets = defaultNoiseConfig().Presets
	}
	return cfg, nil
}

// saveNoiseConfig writes the config atomically — temp file then rename — so an
// interrupted write cannot leave the box with a half-parsed schedule.
func saveNoiseConfig(cfg noiseConfig) error {
	p, err := noiseConfigPath()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return err
	}
	b, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(p), ".hesplay-*.json")
	if err != nil {
		return err
	}
	name := tmp.Name()
	defer os.Remove(name) // no-op once the rename below succeeds
	if _, err := tmp.Write(append(b, '\n')); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(name, 0o644); err != nil {
		return err
	}
	return os.Rename(name, p)
}

// findPreset resolves a preset by name, case-insensitively, falling back to the
// configured default when the name is empty.
func (cfg noiseConfig) findPreset(name string) (noisePreset, error) {
	name = strings.TrimSpace(name)
	if name == "" {
		name = cfg.Default
	}
	if name == "" && len(cfg.Presets) > 0 {
		return cfg.Presets[0], nil
	}
	for _, p := range cfg.Presets {
		if strings.EqualFold(p.Name, name) {
			return p, nil
		}
	}
	names := make([]string, 0, len(cfg.Presets))
	for _, p := range cfg.Presets {
		names = append(names, p.Name)
	}
	return noisePreset{}, fmt.Errorf("no noise preset %q (have: %s)", name, strings.Join(names, ", "))
}

// normalize clamps every field into a range SoX will accept and a human will
// tolerate, and fills a usable default for anything left at zero. It never
// returns an error for an out-of-range number: a preset edited to something
// silly should still make noise, just sane noise. An unknown TYPE is the one
// exception, because there is no sensible clamp for a waveform name.
func (p noisePreset) normalize() (noisePreset, error) {
	out := p
	out.Type = strings.ToLower(strings.TrimSpace(out.Type))
	if out.Type == "" {
		out.Type = "brownnoise"
	}
	// Accept the bare colour ("brown") as well as SoX's name ("brownnoise"),
	// since the original script's variable held the bare form.
	if !strings.HasSuffix(out.Type, "noise") {
		out.Type += "noise"
	}
	if !knownNoiseType(out.Type) {
		return noisePreset{}, fmt.Errorf("unknown noise type %q (have: %s)", p.Type, strings.Join(noiseTypes, ", "))
	}

	out.CenterHz = clampFloat(out.CenterHz, 20, 20000, 1786)
	out.WidthHz = clampFloat(out.WidthHz, 1, 20000, 499)
	out.WaveSpeed = clampFloat(out.WaveSpeed, 0.001, noiseMaxWaveSpeed, 0.08)
	out.WaveDepth = clampFloat(out.WaveDepth, 0, 100, 37)
	out.Reverb = clampFloat(out.Reverb, 0, 100, 19)
	out.FadeIn = clampFloat(out.FadeIn, 0, 300, 0)
	// Gain's zero value is meaningful (leave the level alone), so it is clamped
	// but never defaulted.
	out.GainDB = math.Max(-60, math.Min(20, out.GainDB))

	// The second swell: zero (and any negative) means OFF, so clampFloat's
	// default-substitution must not apply — a silly value switches the feature
	// off rather than on.
	if out.Wave2Speed > 0 {
		out.Wave2Speed = math.Max(0.001, math.Min(noiseMaxWaveSpeed, out.Wave2Speed))
		out.Wave2Depth = clampFloat(out.Wave2Depth, 0, 100, 60)
	} else {
		out.Wave2Speed, out.Wave2Depth = 0, 0
	}
	out.Wave2Type = strings.ToLower(strings.TrimSpace(out.Wave2Type))
	if out.Wave2Type != "" {
		if !strings.HasSuffix(out.Wave2Type, "noise") {
			out.Wave2Type += "noise"
		}
		if !knownNoiseType(out.Wave2Type) {
			return noisePreset{}, fmt.Errorf("unknown second-layer noise type %q (have: %s)", p.Wave2Type, strings.Join(noiseTypes, ", "))
		}
		// Both layer constraints are structural, not taste. The layer chain
		// envelopes the FIRST synth alone, so the second layer must be a colour
		// SoX can synthesize mid-chain; and an ffmpeg-generated base arrives by
		// pipe, leaving no seat in the chain for a separately-enveloped layer.
		if _, ffm := ffmpegColors[out.Wave2Type]; ffm {
			return noisePreset{}, fmt.Errorf("second-layer colour %q needs ffmpeg; the layer must be one SoX can synthesize (white, pink, brown, tpdf)", p.Wave2Type)
		}
		if _, ffm := ffmpegColors[out.Type]; ffm {
			return noisePreset{}, fmt.Errorf("a layered preset's base colour must be one SoX can synthesize (white, pink, brown, tpdf), not %q", p.Type)
		}
		// A layer with no swell is not the feature — fill the usable default.
		if out.Wave2Speed == 0 {
			out.Wave2Speed, out.Wave2Depth = 0.02, 60
		}
	}
	out.Wave2Gain = math.Max(-60, math.Min(20, out.Wave2Gain))
	if out.Wave2Speed > 0 {
		out.Wave2Offset = math.Max(0, math.Min(noiseMaxBufferSecs, out.Wave2Offset))
	} else {
		out.Wave2Offset = 0
	}

	// The floor: any known colour (its own process, so ffmpeg colours are fine
	// here, unlike Wave2Type). Its gain follows the GainDB rule — clamped,
	// never defaulted — because 0 is meaningful; the shipped presets carry −30.
	out.FloorType = strings.ToLower(strings.TrimSpace(out.FloorType))
	if out.FloorType != "" {
		if !strings.HasSuffix(out.FloorType, "noise") {
			out.FloorType += "noise"
		}
		if !knownNoiseType(out.FloorType) {
			return noisePreset{}, fmt.Errorf("unknown floor noise type %q (have: %s)", p.FloorType, strings.Join(noiseTypes, ", "))
		}
		out.FloorCenterHz = clampFloat(out.FloorCenterHz, 20, 20000, 4500)
		out.FloorWidthHz = clampFloat(out.FloorWidthHz, 1, 20000, 2000)
		if out.FloorSpeed > 0 {
			out.FloorSpeed = math.Max(0.001, math.Min(noiseMaxWaveSpeed, out.FloorSpeed))
			out.FloorDepth = clampFloat(out.FloorDepth, 0, 100, 18)
		} else {
			out.FloorSpeed, out.FloorDepth = 0, 0
		}
		out.FloorGain = math.Max(-60, math.Min(20, out.FloorGain))
		if out.FloorSpeed > 0 {
			out.FloorOffset = math.Max(0, math.Min(noiseMaxBufferSecs, out.FloorOffset))
		} else {
			out.FloorOffset = 0
		}
	} else {
		out.FloorCenterHz, out.FloorWidthHz = 0, 0
		out.FloorSpeed, out.FloorDepth, out.FloorGain, out.FloorOffset = 0, 0, 0, 0
	}
	return out, nil
}

func knownNoiseType(t string) bool {
	for _, k := range noiseTypes {
		if k == t {
			return true
		}
	}
	return false
}

// clampFloat bounds v into [lo,hi], substituting def for a non-positive or
// non-finite value so a zeroed JSON field lands on something usable.
func clampFloat(v, lo, hi, def float64) float64 {
	if math.IsNaN(v) || math.IsInf(v, 0) || v <= 0 {
		v = def
	}
	return math.Max(lo, math.Min(hi, v))
}

// bufferSecs is the length of the synthesized buffer that gets repeated.
//
// It is DERIVED, never configured, and that is the whole point. The original
// hardcoded a 60s buffer while running the swell at 0.08 Hz — a 12.5s period —
// which is 4.8 swells per buffer, so the volume envelope jumped mid-swell at
// every loop point. Rounding up to a whole number of swells makes the loop
// seamless without changing the sound at all. A knob here could only ever be
// set to a value that seams.
func (p noisePreset) bufferSecs() float64 {
	period := 1 / p.WaveSpeed
	if p.Wave2Speed > 0 {
		return commensurateBufferSecs(period, 1/p.Wave2Speed)
	}
	n := math.Ceil(noiseMinBufferSecs / period)
	if n < 1 {
		n = 1
	}
	return n * period
}

// commensurateBufferSecs extends the whole-number-of-swells rule to two swells:
// the shortest buffer ≥ the floor that holds a WHOLE number of BOTH periods, so
// the loop stays seamless for both envelopes (the default 12.5s + 50s pair
// lands on 100s — 8 fast swells, 2 slow). Scanning multiples of the longer
// period keeps the search tiny.
//
// An incommensurate pair that fits nothing under noiseMaxBufferSecs settles for
// whole LONG periods only: the slow envelope — the one whose mid-swell jump
// would read as the sea skipping — stays seamless, and the fast swell seams at
// worst once per buffer, the original script's every-60s jump but rarer. A slow
// period longer than the cap itself inverts that: whole fast periods, and the
// slow envelope seams (the user asked for a swell longer than the memory the
// buffer may spend).
func commensurateBufferSecs(p1, p2 float64) float64 {
	long, short := math.Max(p1, p2), math.Min(p1, p2)
	if long > noiseMaxBufferSecs {
		return math.Max(1, math.Ceil(noiseMinBufferSecs/short)) * short
	}
	fallback := 0.0
	for t := long; t <= noiseMaxBufferSecs+1e-9; t += long {
		if t < noiseMinBufferSecs {
			continue
		}
		if fallback == 0 {
			fallback = t
		}
		n := t / short
		if math.Abs(n-math.Round(n)) < 1e-6 {
			return t
		}
	}
	return fallback
}

// repeatCount is the `repeat` argument: how many EXTRA times the buffer plays
// after the first. Sized to the safety cap, not to the session length — see
// noiseSafetyCapSecs.
func (p noisePreset) repeatCount() int {
	n := int(math.Ceil(noiseSafetyCapSecs/p.bufferSecs())) - 1
	if n < 0 {
		n = 0
	}
	return n
}

// noiseArgs builds the `play` argument vector.
//
// Effect ORDER is load-bearing. `repeat` replays everything before it in the
// chain, so `gain` and `fade` must come AFTER it: a fade placed before the
// repeat would re-fade on every single loop iteration, turning a one-time
// ease-in into a pulse every buffer length.
func (p noisePreset) noiseArgs() []string {
	if p.noiseNeedsFFmpeg() {
		return p.soxPipeArgs()
	}
	a := []string{
		"--buffer", strconv.Itoa(noiseBuffer),
		"--no-show-progress",
		"-c", strconv.Itoa(noiseChannels),
		"--null",
	}
	a = append(a, p.synthChain()...)
	a = append(a, p.shapeArgs()...)
	// repeat sits between the shaping and the level/fade for the same reason the
	// comment above gives: everything BEFORE it is what gets replayed.
	a = append(a, "repeat", strconv.Itoa(p.repeatCount()))
	return append(a, p.finishArgs()...)
}

// synthChain is the body's generation: one colour, or the two-colour layered
// form. The slow-wave layer synthesizes FIRST so its gain trim and tremolo
// envelope it ALONE; the base colour then mixes in un-swelled underneath
// (`synth <type> mix` adds onto the flowing audio — the construct is pinned by
// TestNoiseLayeredChainEscapesFirstTremolo). Everything after the mix — band,
// the fast swell, reverb — shapes the sum, so both layers share the timbre
// tuned by ear for brown.
func (p noisePreset) synthChain() []string {
	if p.Wave2Type == "" {
		return []string{"synth", num(p.synthSecs()), p.Type}
	}
	a := []string{"synth", num(p.synthSecs()), p.Wave2Type}
	if p.Wave2Gain != 0 {
		a = append(a, "gain", num(p.Wave2Gain))
	}
	a = append(a, "tremolo", num(p.Wave2Speed), num(p.Wave2Depth))
	if p.Wave2Offset > 0 {
		// The offset trim: shifts the slow layer's envelope against the
		// post-mix fast swell. The synth ran Wave2Offset seconds long, so the
		// post-trim remainder is still a whole number of both periods.
		a = append(a, "trim", num(p.Wave2Offset))
	}
	return append(a, "synth", p.Type, "mix")
}

// synthSecs is the synth length: the loop length plus the offset trim's head,
// which the trim discards before the loop is cut.
func (p noisePreset) synthSecs() float64 {
	return p.bufferSecs() + p.Wave2Offset
}

// bodySoxArgs renders the body — the preset's one- or two-layer sea — as a
// generator stage for the floor topology: the same chain noiseArgs plays, but
// writing sox-format samples to stdout for the mixer, and without the fade
// (the mixer fades the MIX once). GainDB stays here: it is the body's level,
// and the floor's own gain is relative to an un-faded, gained body — exactly
// the balance the audition's independent processes had.
func (p noisePreset) bodySoxArgs() []string {
	var a []string
	if p.noiseNeedsFFmpeg() {
		a = []string{"--buffer", strconv.Itoa(noiseBuffer), "-t", "wav", "-", "-t", "sox", "-"}
		a = append(a, p.shapeArgs()...)
	} else {
		a = []string{"--buffer", strconv.Itoa(noiseBuffer), "-c", strconv.Itoa(noiseChannels), "--null", "-t", "sox", "-"}
		a = append(a, p.synthChain()...)
		a = append(a, p.shapeArgs()...)
		a = append(a, "repeat", strconv.Itoa(p.repeatCount()))
	}
	if p.GainDB != 0 {
		a = append(a, "gain", num(p.GainDB))
	}
	return a
}

// floorBufferSecs / floorRepeatCount are the floor's own loop-seam math: whole
// floor-swell periods (a still floor loops raw noise, statistically seamless
// at any length, so it keeps the plain 60s). Only the SoX-native floor loops —
// an ffmpeg-generated floor streams continuously and has no seam at all.
func (p noisePreset) floorBufferSecs() float64 {
	if p.FloorSpeed <= 0 {
		return noiseMinBufferSecs
	}
	period := 1 / p.FloorSpeed
	n := math.Ceil(noiseMinBufferSecs / period)
	if n < 1 {
		n = 1
	}
	return n * period
}

func (p noisePreset) floorRepeatCount() int {
	n := int(math.Ceil(noiseSafetyCapSecs/p.floorBufferSecs())) - 1
	if n < 0 {
		n = 0
	}
	return n
}

// floorSoxArgs shapes the floor layer, output sox-format for the mixer. The
// attenuation comes FIRST — the raw generator sits near full scale and the
// bright band rings, and gain ahead of it removes the clipping the audition
// chain logged ("band clipped 22 samples"); the chain is linear, so the sound
// is otherwise identical. The floor shares the preset's reverb, so it sits in
// the same room as the sea above it.
func (p noisePreset) floorSoxArgs() []string {
	var a []string
	if p.floorNeedsFFmpeg() {
		a = []string{"--buffer", strconv.Itoa(noiseBuffer), "-t", "wav", "-", "-t", "sox", "-"}
	} else {
		a = []string{"--buffer", strconv.Itoa(noiseBuffer), "-c", strconv.Itoa(noiseChannels), "--null", "-t", "sox", "-",
			"synth", num(p.floorBufferSecs() + p.FloorOffset), p.FloorType}
	}
	if p.FloorGain != 0 {
		a = append(a, "gain", num(p.FloorGain))
	}
	a = append(a, "band", "-n", num(p.FloorCenterHz), num(p.FloorWidthHz))
	if p.FloorSpeed > 0 {
		a = append(a, "tremolo", num(p.FloorSpeed), num(p.FloorDepth))
		if p.FloorOffset > 0 {
			// Shifts the floor's breath against the body's tide — the mixer
			// syncs both streams' sample 0, so a trimmed head is a pure
			// phase offset between the layers.
			a = append(a, "trim", num(p.FloorOffset))
		}
	}
	a = append(a, "reverb", num(p.Reverb))
	if !p.floorNeedsFFmpeg() {
		a = append(a, "repeat", strconv.Itoa(p.floorRepeatCount()))
	}
	return a
}

// mixerArgs mixes body and floor onto the device at unity. Plain `-m` scales
// each input by 1/n — measured: two identical in-phase sines mixed read the
// SAME RMS as one — which would quietly halve the whole preset, so `-v 1` per
// input restores the straight sum the audition's sound server gave. The two
// /dev/fd paths are wired by the runner via ExtraFiles (first extra file = fd
// 3); no shell is involved.
func (p noisePreset) mixerArgs() []string {
	a := []string{
		"--buffer", strconv.Itoa(noiseBuffer),
		"--no-show-progress",
		"-m",
		"-v", "1", "-t", "sox", "/dev/fd/3",
		"-v", "1", "-t", "sox", "/dev/fd/4",
	}
	if p.FadeIn > 0 {
		a = append(a, "fade", "t", num(p.FadeIn))
	}
	return a
}

// shapeArgs is the timbre: band-pass, the slow swell, and reverb. Identical on
// both paths, so a hybrid colour is shaped by exactly the chain that was tuned
// by ear for brown.
func (p noisePreset) shapeArgs() []string {
	a := []string{
		"band", "-n", num(p.CenterHz), num(p.WidthHz),
		"tremolo", num(p.WaveSpeed), num(p.WaveDepth),
	}
	if p.Wave2Speed > 0 && p.Wave2Type == "" {
		// Chained tremolos multiply their envelopes: the slow one is the tide,
		// the fast one rides it. (With Wave2Type set the slow swell already
		// lives on its own layer, before this chain.) The offset trim between
		// them shifts the fast envelope against the slow so the tide crest
		// lands between wave crests instead of always on one.
		if p.Wave2Offset > 0 {
			a = append(a, "trim", num(p.Wave2Offset))
		}
		a = append(a, "tremolo", num(p.Wave2Speed), num(p.Wave2Depth))
	}
	return append(a, "reverb", num(p.Reverb))
}

// finishArgs is level then fade — always last, and on the native path always
// after `repeat`.
func (p noisePreset) finishArgs() []string {
	var a []string
	if p.GainDB != 0 {
		a = append(a, "gain", num(p.GainDB))
	}
	if p.FadeIn > 0 {
		a = append(a, "fade", "t", num(p.FadeIn))
	}
	return a
}

// soxPipeArgs is the SoX side of the hybrid: read the generated stream from
// stdin and shape it.
//
// There is deliberately no `synth` and no `repeat`. ffmpeg generates
// continuously, so there is no buffer to loop — which also means the hybrid
// path has no loop seam to fix, and `repeat` would be actively wrong here
// (SoX's repeat buffers its input to replay it, and this input never ends).
// Nor `-c 2`: on the native path that describes the null input device, but here
// the channel count comes from the piped WAV header.
func (p noisePreset) soxPipeArgs() []string {
	a := []string{
		"--buffer", strconv.Itoa(noiseBuffer),
		"--no-show-progress",
		"-t", "wav", "-",
	}
	a = append(a, p.shapeArgs()...)
	return append(a, p.finishArgs()...)
}

// ffmpegArgs is the generator side of the hybrid. -t caps it at the same 24h
// safety ceiling `repeat` gives the native path, for the same reason: a hesplay
// that dies without reaping its children must not leave the box roaring.
func (p noisePreset) ffmpegArgs() []string {
	return ffmpegArgsFor(ffmpegColors[p.Type])
}

// ffmpegArgsFor generates one anoisesrc colour — the body's or the floor's.
func ffmpegArgsFor(colour string) []string {
	return []string{
		"-hide_banner", "-loglevel", "error",
		"-f", "lavfi",
		"-i", fmt.Sprintf("anoisesrc=color=%s:r=%d:d=%d", colour, noiseSampleRate, noiseSafetyCapSecs),
		// anoisesrc is mono; the native path plays two channels, so match it.
		"-ac", strconv.Itoa(noiseChannels),
		"-f", "wav", "-",
	}
}

// num formats a float the way a person would write it: no trailing zeros, no
// exponent. SoX parses these as plain seconds/Hz/percent.
func num(f float64) string {
	return strconv.FormatFloat(f, 'f', -1, 64)
}

// noisePlayer is the SoX playback binary. `play` is SoX's playback front-end;
// it is what the original script used and what both target boxes have. sox is
// the same binary in file-to-file dress — the floor topology's generator
// stages MUST use it, not play: play hardwires its output to the audio device,
// so a stage exec'd as play ignores the intended `-t sox -` stdout, opens the
// speakers itself, and the mixer starves (the live failure mode of the first
// runNoiseFloor: three processes on the device, then instant EOF).
type noisePlayer struct {
	path string // play — owns the audio device
	sox  string // sox — file/pipe stages only
}

func findNoisePlayer() (noisePlayer, error) {
	p, err := exec.LookPath("play")
	if err != nil {
		return noisePlayer{}, errors.New("no noise engine: install sox (provides `play`)")
	}
	s, err := exec.LookPath("sox")
	if err != nil {
		// Same package ships both; a play without sox is a broken install.
		return noisePlayer{}, errors.New("no noise engine: install sox (`play` is present but `sox` is not)")
	}
	return noisePlayer{path: p, sox: s}, nil
}

// noiseGenerator is ffmpeg, needed only by the colours SoX cannot synthesize.
type noiseGenerator struct{ path string }

func findNoiseGenerator() (noiseGenerator, error) {
	p, err := exec.LookPath("ffmpeg")
	if err != nil {
		return noiseGenerator{}, errors.New("blue, violet and velvet noise are generated by ffmpeg, which is not installed (the other colours need only sox)")
	}
	return noiseGenerator{path: p}, nil
}

// noiseEnv is the environment for the play process. The original systemd unit
// set AUDIODRIVER=alsa and AUDIODEV=plughw:0 to pin the output; carrying that
// through config matters because SoX's default device need not be the one mpv
// picks, and a wrong-sink failure is silent.
func noiseEnv(audioDev string) []string {
	env := os.Environ()
	if d := strings.TrimSpace(audioDev); d != "" {
		env = append(env, "AUDIODRIVER=alsa", "AUDIODEV="+d)
	}
	return env
}

// runNoise plays one preset until the context is cancelled or the safety cap
// runs out. Cancelling kills the process — that is how a session ends, and why
// `repeat` is only a backstop rather than the timer.
//
// onStart (may be nil) receives the PLAYER process once it is running — the one
// that owns the audio device — which is what the remote's pause signals. It is
// a callback rather than a return value because this function blocks for the
// whole session.
//
// There is no stall guard here, unlike the music engine: SoX exposes no IPC
// socket, so a process that is alive but silent cannot be distinguished from
// one that is working. A process that EXITS is detectable and the caller
// restarts it; a wedged one is a known, accepted gap.
func runNoise(ctx context.Context, pl noisePlayer, p noisePreset, audioDev string, onStart func(*os.Process)) error {
	if p.floorActive() {
		return runNoiseFloor(ctx, pl, p, audioDev, onStart)
	}
	if p.noiseNeedsFFmpeg() {
		return runNoiseHybrid(ctx, pl, p, audioDev, onStart)
	}
	cmd := exec.CommandContext(ctx, pl.path, p.noiseArgs()...)
	cmd.Env = noiseEnv(audioDev)
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("%s: %w", filepath.Base(pl.path), err)
	}
	if onStart != nil {
		onStart(cmd.Process)
	}
	if err := cmd.Wait(); err != nil {
		if ctx.Err() != nil {
			return nil // cancelled: the intended way to stop
		}
		return fmt.Errorf("%s: %w", filepath.Base(pl.path), err)
	}
	return nil
}

// runNoiseHybrid generates with ffmpeg and shapes with SoX, for the colours SoX
// cannot synthesize.
//
// A real OS pipe rather than StdoutPipe/io.Copy, and both ends closed in the
// parent once the children hold them. That matters for shutdown: with the write
// end held open here, SoX would never see EOF, and with the read end held open
// ffmpeg would never get EPIPE. Closed, the pair tears itself down — if the
// player exits first, the generator dies of a broken pipe on its next write
// instead of lingering as an orphan writing into nothing.
func runNoiseHybrid(ctx context.Context, pl noisePlayer, p noisePreset, audioDev string, onStart func(*os.Process)) error {
	ff, err := findNoiseGenerator()
	if err != nil {
		return err
	}

	gen := exec.CommandContext(ctx, ff.path, p.ffmpegArgs()...)
	shape := exec.CommandContext(ctx, pl.path, p.soxPipeArgs()...)
	shape.Env = noiseEnv(audioDev)

	pr, pw, err := os.Pipe()
	if err != nil {
		return err
	}
	gen.Stdout, gen.Stderr = pw, os.Stderr
	shape.Stdin = pr
	shape.Stdout, shape.Stderr = os.Stdout, os.Stderr

	if err := gen.Start(); err != nil {
		pr.Close()
		pw.Close()
		return fmt.Errorf("%s: %w", filepath.Base(ff.path), err)
	}
	if err := shape.Start(); err != nil {
		pr.Close()
		pw.Close()
		_ = gen.Process.Kill()
		_ = gen.Wait()
		return fmt.Errorf("%s: %w", filepath.Base(pl.path), err)
	}
	pr.Close()
	pw.Close()
	if onStart != nil {
		onStart(shape.Process) // the player, not the generator: pause freezes the device owner
	}

	// Wait on the PLAYER, because it owns the audio device and its exit is what
	// "the noise stopped" means. Then make sure the generator is gone rather
	// than assuming EPIPE got there first — an orphaned ffmpeg would hold no
	// device but would burn CPU forever.
	werr := shape.Wait()
	if gen.Process != nil {
		_ = gen.Process.Kill()
	}
	_ = gen.Wait()

	if werr != nil && ctx.Err() == nil {
		return fmt.Errorf("%s: %w", filepath.Base(pl.path), werr)
	}
	return nil
}

// runNoiseFloor runs the three-layer topology: the body (the preset's one- or
// two-layer sea) and the floor each render in their own SoX stage, and a final
// `play -m` mixes them onto the device at unity. The mixer is what phase-locks
// the floor's swell to the body's: `play -m` reads its inputs
// sample-synchronously, blocking until BOTH deliver, so each stream's t=0
// lines up exactly however long its stage spent starting (the body pre-computes
// a 100s buffer; the floor streams immediately — irrelevant, the mixer waits).
// An ffmpeg generator fronts any stage whose colour SoX cannot synthesize.
//
// Teardown follows runNoiseHybrid's lesson: wait on the DEVICE OWNER (the
// mixer), then explicitly kill every upstream process rather than trusting
// EPIPE, which measured seconds to climb through the 128 KB buffers. Pause
// (SIGSTOP) also lands on the mixer: its full pipes throttle every stage
// upstream, exactly like the hybrid pair.
func runNoiseFloor(ctx context.Context, pl noisePlayer, p noisePreset, audioDev string, onStart func(*os.Process)) error {
	needsFF := p.noiseNeedsFFmpeg() || p.floorNeedsFFmpeg()
	var ff noiseGenerator
	if needsFF {
		var err error
		if ff, err = findNoiseGenerator(); err != nil {
			return err
		}
	}

	var started []*exec.Cmd
	killAll := func() {
		for _, c := range started {
			if c.Process != nil {
				_ = c.Process.Kill()
			}
		}
		for _, c := range started {
			_ = c.Wait()
		}
	}

	// stage wires [optional ffmpeg generator →] one SoX shaping process and
	// returns the read end of its sox-format output pipe. Parent copies of
	// every intermediate fd are closed as soon as both holders have started —
	// the hybrid runner's rule, without which nobody ever sees EOF or EPIPE.
	// Stages exec `sox`, never `play` — see the noisePlayer comment.
	stage := func(genColour string, soxArgs []string) (*os.File, error) {
		outR, outW, err := os.Pipe()
		if err != nil {
			return nil, err
		}
		shape := exec.CommandContext(ctx, pl.sox, soxArgs...)
		shape.Stdout, shape.Stderr = outW, os.Stderr
		if genColour != "" {
			genR, genW, err := os.Pipe()
			if err != nil {
				outR.Close()
				outW.Close()
				return nil, err
			}
			gen := exec.CommandContext(ctx, ff.path, ffmpegArgsFor(genColour)...)
			gen.Stdout, gen.Stderr = genW, os.Stderr
			shape.Stdin = genR
			if err := gen.Start(); err != nil {
				outR.Close()
				outW.Close()
				genR.Close()
				genW.Close()
				return nil, fmt.Errorf("%s: %w", filepath.Base(ff.path), err)
			}
			started = append(started, gen)
			defer genR.Close()
			defer genW.Close()
		}
		if err := shape.Start(); err != nil {
			outR.Close()
			outW.Close()
			return nil, fmt.Errorf("%s: %w", filepath.Base(pl.sox), err)
		}
		started = append(started, shape)
		outW.Close()
		return outR, nil
	}

	bodyColour := ""
	if p.noiseNeedsFFmpeg() {
		bodyColour = ffmpegColors[p.Type]
	}
	floorColour := ""
	if p.floorNeedsFFmpeg() {
		floorColour = ffmpegColors[p.FloorType]
	}

	bodyR, err := stage(bodyColour, p.bodySoxArgs())
	if err != nil {
		killAll()
		return err
	}
	floorR, err := stage(floorColour, p.floorSoxArgs())
	if err != nil {
		bodyR.Close()
		killAll()
		return err
	}

	mix := exec.CommandContext(ctx, pl.path, p.mixerArgs()...)
	mix.Env = noiseEnv(audioDev)
	mix.Stdout, mix.Stderr = os.Stdout, os.Stderr
	// ExtraFiles entry i becomes the child's fd 3+i — the /dev/fd/3 and
	// /dev/fd/4 the mixer argv names.
	mix.ExtraFiles = []*os.File{bodyR, floorR}
	if err := mix.Start(); err != nil {
		bodyR.Close()
		floorR.Close()
		killAll()
		return fmt.Errorf("%s: %w", filepath.Base(pl.path), err)
	}
	bodyR.Close()
	floorR.Close()
	if onStart != nil {
		onStart(mix.Process) // the device owner: pause freezes it, pipes throttle the rest
	}

	werr := mix.Wait()
	killAll()
	if werr != nil && ctx.Err() == nil {
		return fmt.Errorf("%s: %w", filepath.Base(pl.path), werr)
	}
	return nil
}

// cmdNoise is the `noise` verb: play a preset, list them, or print the exact
// SoX invocation without running it.
//
//	hesplay noise                 play the default preset until Ctrl+C
//	hesplay noise brown           play a named preset
//	hesplay noise --for 45 brown  stop after 45 minutes
//	hesplay noise list            list the presets
//	hesplay noise --print brown   print the command, play nothing
//
// Arguments are scanned rather than passed to a FlagSet so a flag may sit
// anywhere, matching the rest of hesplay where a bare name needs no quoting.
func cmdNoise(ctx context.Context, args []string) error {
	var (
		printOnly bool
		list      bool
		minutes   float64
		words     []string
	)
	for i := 0; i < len(args); i++ {
		a := args[i]
		switch {
		case isHelp(a):
			usage()
			return nil
		case a == "--print" || a == "--print-command":
			printOnly = true
		case a == "list":
			list = true
		case a == "--for" || a == "-for":
			if i+1 >= len(args) {
				return errors.New("--for: expected a number of minutes")
			}
			i++
			m, err := strconv.ParseFloat(args[i], 64)
			if err != nil || m <= 0 {
				return fmt.Errorf("--for: %q is not a positive number of minutes", args[i])
			}
			minutes = m
		case strings.HasPrefix(a, "--for="):
			m, err := strconv.ParseFloat(strings.TrimPrefix(a, "--for="), 64)
			if err != nil || m <= 0 {
				return fmt.Errorf("--for: %q is not a positive number of minutes", a)
			}
			minutes = m
		default:
			words = append(words, a)
		}
	}

	cfg, err := loadNoiseConfig()
	if err != nil {
		return err
	}
	if list {
		return listNoisePresets(cfg)
	}

	preset, err := cfg.findPreset(strings.Join(words, " "))
	if err != nil {
		return err
	}
	preset, err = preset.normalize()
	if err != nil {
		return err
	}

	pl, err := findNoisePlayer()
	if err != nil {
		return err
	}
	if printOnly {
		fmt.Println(noiseCommandLine(pl, preset, cfg.AudioDev))
		return nil
	}

	if minutes > 0 {
		fmt.Printf("%s noise for %g minutes (Ctrl+C to stop)\n", preset.Name, minutes)
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, time.Duration(minutes*float64(time.Minute)))
		defer cancel()
	} else {
		fmt.Printf("%s noise (Ctrl+C to stop)\n", preset.Name)
	}
	return runNoise(ctx, pl, preset, cfg.AudioDev, nil)
}

// listNoisePresets prints the configured presets, marking the default. The
// swell period is shown derived rather than raw because "one swell every 12.5s"
// is the thing a person is actually choosing.
func listNoisePresets(cfg noiseConfig) error {
	tw := newTable("NAME", "TYPE", "BAND", "SWELL", "DEPTH", "REVERB", "GAIN")
	for _, p := range cfg.Presets {
		n, err := p.normalize()
		if err != nil {
			return err
		}
		name := n.Name
		if strings.EqualFold(name, cfg.Default) {
			name += " *"
		}
		fmt.Fprintf(tw, "%s\t%s\t%g±%g Hz\t%.1fs\t%g%%\t%g%%\t%+g dB\n",
			name, strings.TrimSuffix(n.Type, "noise"),
			n.CenterHz, n.WidthHz, 1/n.WaveSpeed, n.WaveDepth, n.Reverb, n.GainDB)
	}
	return tw.Flush()
}

// noiseCommandLine renders the invocation for --print-command and for tests.
// Quoting is display-only: the real call passes the vector to exec, so nothing
// here is ever parsed by a shell.
func noiseCommandLine(pl noisePlayer, p noisePreset, audioDev string) string {
	var b strings.Builder
	// A floor preset renders as the mixer line with each stage as a process
	// substitution — bash's <( ) is /dev/fd plumbing, the same mechanism the
	// runner builds with ExtraFiles — so the printed line is paste-able and
	// reproduces exactly what plays.
	if p.floorActive() {
		gen := "ffmpeg"
		if g, err := findNoiseGenerator(); err == nil {
			gen = filepath.Base(g.path)
		}
		sub := func(colour string, soxArgs []string) string {
			var s strings.Builder
			s.WriteString("<(")
			if colour != "" {
				writeCmd(&s, gen, ffmpegArgsFor(colour))
				s.WriteString(" | ")
			}
			writeCmd(&s, "sox", soxArgs)
			s.WriteString(")")
			return s.String()
		}
		bodyColour, floorColour := "", ""
		if p.noiseNeedsFFmpeg() {
			bodyColour = ffmpegColors[p.Type]
		}
		if p.floorNeedsFFmpeg() {
			floorColour = ffmpegColors[p.FloorType]
		}
		if d := strings.TrimSpace(audioDev); d != "" {
			b.WriteString("AUDIODRIVER=alsa AUDIODEV=" + d + " ")
		}
		b.WriteString(filepath.Base(pl.path))
		for _, a := range p.mixerArgs() {
			b.WriteString(" ")
			switch a {
			case "/dev/fd/3":
				b.WriteString(sub(bodyColour, p.bodySoxArgs()))
			case "/dev/fd/4":
				b.WriteString(sub(floorColour, p.floorSoxArgs()))
			default:
				b.WriteString(a)
			}
		}
		return b.String()
	}
	// The hybrid colours render as the pipeline they actually are, so what is
	// printed can be pasted into a shell and reproduce exactly what plays.
	if p.noiseNeedsFFmpeg() {
		gen := "ffmpeg"
		if g, err := findNoiseGenerator(); err == nil {
			gen = filepath.Base(g.path)
		}
		writeCmd(&b, gen, p.ffmpegArgs())
		b.WriteString(" | ")
	}
	if d := strings.TrimSpace(audioDev); d != "" {
		b.WriteString("AUDIODRIVER=alsa AUDIODEV=" + d + " ")
	}
	writeCmd(&b, filepath.Base(pl.path), p.noiseArgs())
	return b.String()
}

// writeCmd appends `name arg arg …`, quoting only what a shell would need
// quoted. Display-only: the real calls pass vectors to exec, so nothing here is
// ever parsed by a shell.
func writeCmd(b *strings.Builder, name string, args []string) {
	b.WriteString(name)
	for _, a := range args {
		b.WriteString(" ")
		if a == "" || strings.ContainsAny(a, " \t|&;<>()$`\\\"'") {
			b.WriteString(strconv.Quote(a))
			continue
		}
		b.WriteString(a)
	}
}
